version: "3.7"

services:
  nginx:
    image: woneee99/nginx
    restart: always
    container_name: nginx
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - frontend
  client:
    build:
      context: ./ 
      dockerfile: Dockerfile
    networks:
      - frontend
  
networks:
  frontend:
    driver: bridge

